### ISSUE TITLE
Issue Pulling Misc. Team Stats - Defense without Defining a 'season'

### ISSUE THREAD

**Issue by ashayotovich** [j-andrews7/kenpompy#7]
I am working on using the package to pull the Miscellaneous Team Stats - Defense page and am encountering an error. I successfully pulled the Offense page with the first line, but the second line (to pull the defense data) is bombing. 

![image](https://user-images.githubusercontent.com/78546960/106938491-0dd0c480-66ed-11eb-84f2-17f9fa93d480.png)

In your summary.py file where you define your get_teamstats function, it looks like there is a small typo on line 150:
url = url + '?od=d'

the '?' should be an '&' sign.

You have this correct in line 147, but since that is within the 'if season:' loop, it forces the user to insert a season. By updating line 150 to the correct syntax, I think it would allow users to request the Defense data without defining a season (which on the website defaults to current season).

![image](https://user-images.githubusercontent.com/78546960/106938310-cfd3a080-66ec-11eb-872c-6f5982ed570e.png)

As I was writing this, inserted a value for 'season' and was able to pull the data. Just a potential enhancement I noticed. Thanks for the package, its awesome!

**Comment by j-andrews7** [comment]
Hey, thanks for finding and troubleshooting this. I am certain there are
other bugs - I haven't touched this in over a year and I'm sure Ken's
updated his site since then.

I definitely need to get back to it since basketball's back again, the
tests have been screaming at me that some have been failing for months.

Maybe this will be the impetus to get me going on it again since it's such
an easy fix.

**Comment by j-andrews7** [comment]
This should be fixed in the latest release.
